language: node_js
node_js:
  - stable
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test
  - yarn build
notifications:
  email: false
branch:
  only:
    - develop
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: dist
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: master
  on:
    tags: true
